### ISSUE TITLE
SimpleCLI version given in platformio.ini is incorrect

### ISSUE THREAD

**Issue by arnuschky** [ASealion/EnRav#13]
This code seems to depend on a pre-release version of SimpleCLI. Version 1.0.0 and all following versions don't seem to be using namespaces. However, `platformio.ini` specifies `SimpleCLI@1.0.0`. Therefore, the project does not compile. 

Could you please tell me which SimpleCLI git commit works with this project?

**Comment by ASealion** [comment]
Unfortunately the version given in the platformio.ini is correct but the author changed his code without updating the version number.

As as far I could see, this should be the correct version that I used :
[https://github.com/spacehuhn/SimpleCLI/tree/21cc0bb4df39b1525fe089f869be3dbde5b4ba0b](url)

**Comment by arnuschky** [comment]
:+1: perfect, thanks. Works like a charm.
